# nonk8s
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prodspek_fkb_ar5
  tags: [public]
  links:
    - url: https://github.com/kartverket/prodspek_fkb_ar5
      title: prodspek_fkb_ar5 på GitHub
spec:
  type: service
  lifecycle: production
  owner: matrikkel
  system: matrikkel
  dependsOn:
    - resource:default/SKIP
  providesApis:
    - prodspek_fkb_ar5-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: prodspek_fkb_ar5-api
  tags: [public]
spec:
  type: openapi
  lifecycle: production
  owner: matrikkel
  system: matrikkel
  definition: |
    openapi: "3.0.0"
    info:
      title: prodspek_fkb_ar5 API
    paths:
