:datasett: FKB-AR5
:publisert: 2024-07-01
:versjon: 5.1
:skjemaversjon: 5.1
:versjon-forrige: 5.0
:versjon-erstattet-av: 5.1
:underversjon: 2024-07-01
:underversjon-forrige: 2022-01-01
:metadata-url: https://kartkatalog.geonorge.no/metadata/fkb-ar5/166382b4-82d6-4ea9-a68e-6fd0c87bf788
:dokumentstatus: 1
// All informasjon i hode over denne linja må fylles ut for hvert datasett.
include::../felles/filhode.adoc[]

== Innledning, historikk og endringslogg

=== Innledning
FKB-AR5 er en del av Felles Kartdatabase (FKB). FKB-spesifikasjonen er en serie produktspesifikasjoner for detaljerte basis geodata som samles inn og forvaltes gjennom Geovekst. Generelle beskrivelser for alle FKB-spesifikasjonene er samlet i FKB-Generell del <<FKB>>.

AR5 er et heldekkende arealressursdatasettet som bekriver alt areal ved hjelp av fire egenskaper; arealtype, treslag, skogbonitet og grunnforhold. 

Denne produktspesifikasjonen er utarbeidet iht. SOSI produktspesifikasjoner – Krav og godkjenning 5.0 <<SOSI-KRAV>>. UML-modellen som ligger til grunn for innhold i diagrammene og dokumentasjon i kap. 5, følger reglene i SOSI Regler for UML-modellering, versjon 5.1 <<SOSI-UML>>. http://sosi.geonorge.no/veiledere/UML[Denne veilederen] gir hjelp til å lese UML-diagrammene.


=== Historikk

Tidligere versjoner:

* FKB versjon 3.3 oktober 2001
* FKB versjon 3.4 august 2002
* FKB-AR5 versjon 4.0 – 2007-01-01
* FKB-AR5 versjon 4.01 - 2009-03-10
* FKB-AR5 versjon 4.02 - 2011-12-01
* FKB-AR5 versjon 4.5 - 2014-03-01
* FKB-AR5 versjon 4.6 - 2016-07-01
* FKB-AR5 versjon 5.0 - 2022-01-01

=== Endringslogg

==== Endringer fra FKB-AR5 5.0.1 til FKB-AR5 5.1

* Lagt til taggen inlineOrByReference=byReference på alle assosiasjoner 

==== Endringer fra FKB-AR5 5.0 til FKB-AR5 5.0.1

* Lagt inn manglende defaultCodeSpace-tag på egenskapen registreringsversjon i abstrakt featuretype Fellesegenskaper
* Justert på innholdet i kodelistene _Opphav_ og _Klassifiseringsmetode_ (nevnes i endringsloggen for oversiktens skyld selv om endringer i kodelister kan gjøres uten oppdatering av UML-modell/produktspesifikasjon) 

==== Endringer fra FKB-AR5 4.6 til FKB-AR5 5.0

* Oppdatert generelle konsepter fra FKB 5.0 generell del. Se <<FKB>> for detaljer.
* Egenskapen ARKartstandard utgår
* Kodeliste Klassifiseringsmetode innført. Kodelista benyttes på egenskapen Klassifiseringsmetode som er innført på objekttype Arealressursflate.
* Opphav endret fra fritekst til kodeliste

=== Normative referanser

include::../felles/kap14_normativ_ref.adoc[]

<<<

== Definisjoner og forkortelser

=== Definisjoner

include::../felles/kap21_definisjoner.adoc[]

=== Forkortelser

include::../felles/kap22_forkortelser.adoc[]

<<<

== Generelt om spesifikasjonen

=== Unik identifisering
FKBAR5

==== Fullstendig navn
{datasett} 

==== Versjon
{versjon}

=== Referansedato
{underversjon}

=== Ansvarlig organisasjon
Geovekst (fagansvarlig NIBIO)

=== Språk
nor

=== Hovedtema
Basisdata, arealressurs, markslag

=== Temakategori
basisData

=== Sammendrag
AR5 er et heldekkende arealressursdatasettet som bekriver alt areal ved hjelp av fire egenskaper; arealtype, treslag, skogbonitet og grunnforhold. 

=== Formål
// Fellesdel for FKB generell del og alle FKB-produktspesifikasjoner
include::../felles/kap38_formal.adoc[]

FKB-AR5 brukes som grunnlag for utbetalinger av arealstøtte til landbruket.

// Fellesdel som dekker kap 3.9 - 3.12 for alle FKB-produktspesifikasjoner
include::../felles/kap39-312_representasjon.adoc[]

=== Supplerende beskrivelse
Data ikke angitt



<<<

== Spesifikasjonsomfang

include::../felles/kap4_omfang.adoc[]

<<<

== Innhold og struktur

=== Omfang
<<HeleDatasettet,Hele datasettet>>


include::modellRapport.adoc[]

<<<

== Referansesystem

include::../felles/kap6_referansesystem.adoc[]

<<<

== Kvalitet

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Beskrivelse av datakvalitet
For AR5 inneholder data fra flere kilder (se kapittel 8 og kapittel 9). AR5 er basert på markslag i økonomisk kartverk, som ble kartlagt i tidsrommet 1960-1990. Første versjon av AR5 ble avleda fra digitalt markslagskart (DMK) i 2008.

For å få et godt bilde av kvaliteten til data innenfor et område må man derfor vurdere datakvaliteten (metadata) til kartobjektene. Det vil også være mulig å aggregere denne informasjonen som finnes på objektnivå opp til en beskrivelse av kvaliteten på datainnholdet i området som helhet. Det er imidlertid vanskelig å garantere datakvaliteten for FKB innenfor et område.

<<<

== Datafangst
=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Periodisk ajourhold
For AR5 skjer den dominerende mengden av ny datafangst gjennom prosjekter for periodisk ajourhold. Prosjektene styres/finansieres stort sett gjennom Geovekst, men den faglige og praktiske delen av jobben gjøres av NIBIO med bakgrunn i flybilder/ortofoto og ev. andre datakilder. 

Se http://www.nibio.no for mer informasjon.

<<<

== Datavedlikehold

include::kap9_vedlikehold.adoc[]

<<<

== Presentasjon

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Referanse til presentasjonskatalog
Presentasjonsregler for FKB-data er angitt i skjermkartografispesifikasjonen: https://register.geonorge.no/register/versjoner/tegneregler/geovekst/fkb-skjermkartografi

<<<

== Leveranse

include::../felles/kap11_leveranse.adoc[]

<<<

== Tilleggsinformasjon

For å forstå kravene til registrering av AR5 er det nødvendig å sette seg inn i 
klassifikasjonssystemet for AR5. Se publikasjon «AR5 Klassifikasjonssystem», www.nibio.no.

==== Kartteknisk kortversjon av klassifikasjonssystem og instruks 
Klassifikasjonssystemet ‘AR5’ har 106 lovlige kombinasjoner av egenskapsverdiene for Arealtype, Treslag, Skogbonitet og Grunnforhold. De lovlige kombinasjonene framgår av Vedlegg C. 
SOSI-kontroll har kombinasjonssjekk. De mest brukte kartverktøyene for AR5-ajourhold, har også egen sjekk av kombinasjonene. 

Symboler (signatur) for AR5-egenskapene skal tegnes i rekkefølgen Arealtype (ARTYPE), Treslag (ARTRESLAG), Skogbonitet (ARSKOGBON) og Grunnforhold (ARGRUNNF), se publikasjon «Kartografi for AR5» på http://www.nibio.no. 

Det er et prinsipp at alt areal skal dekkes av flateobjekter i AR5. Dette for å unngå tvil om et areal er kartlagt eller ikke. Flateobjekter i områder som ikke er kartlagt, klassifiseres med arealtypen ’ikke kartlagt’ inntil det er gjort kartlegging av AR5. 

Et annet viktig prinsipp er at objektene skal ha angitt eksplisitt verdi for alle egenskaper. Der egenskapen ikke er registrert eller ikke er relevant, skal dette angis med definert verdi. Dette hindrer tvil eller misforståelser som kan oppstå ved manglende verdier, ’0’ ’null’ for eksempel ved konvertering mellom ulike formater. 

Det skal ikke registreres høydeverdier på noen AR5-objekter. Dersom man vil gjøre analyser som krever høydeinformasjon eller gjøre 3D-framstillinger skal man hente høydedata fra egnet datakilde, og evt. gjøre en midlertidig tilordning av disse på AR5-dataene. 

For å hindre at AR5-flater blir uhåndterlig store, kan det brukes fiktiv grense for å dele flater som ellers har like egenskaper. Her benyttes den fagspesifikke objekttypen ArealressursGrenseFiktiv. Vi presiserer at denne objekttypen ikke skal ha Verifiseringsdato. 

Ved uttak av data må det legges ytterkant på valgt utsnitt; enten det er et tilfeldig polygon, kommune eller kartblad. Her brukes den generelle objekttypen KantUtsnitt. 

Ved uttak av tilfeldige områder (utsnitt) til blant annet analyser, vil ArealressursGrenseFiktiv være interne grenser som man normalt ønsker å fjerne. 

Se veileder («kokebok») for AR5-ajourhold i kommunens eget kartverktøy på http://www.nibio.no.

===== Metadata på objektene i AR5

*Posisjonskvalitet*

Alle grenser, skal ha kvalitetsegenskaper som beskriver den reelle kvaliteten best mulig. Verdier for datafangstmetode, nøyaktighet og synbarhet skal i prinsippet settes uavhengig av hverandre. 

* Datafangstmetode angis på grenser i AR5. 
+
Merknad: De mest vanlige datafangstmetodene for registering av grenser vil være,
«digitalisert» (dig) og «satelittmålt» (sat). Grenser som kopieres inn fra andre kartbaser, beholder sin opprinnelige datafangstmetode. Se egen kodeliste for datafangstmetode.

* Nøyaktighet angis på grenser i AR5 i cm ut fra nøyaktigheten til registreringsgrunnlaget og hvor godt definert detaljen er i terrenget. Det generelle kravet til stedfestingsnøyaktighet er 2 meter. 

* Synbarhet angis på grenser iht. spesielle regler for AR5, som er en tillemping av de generelle reglene. 
** Sikker registrering: Synbarhet = 0 (fullt ut synlig) 
** Svært usikker registrering: Synbarhet = 3 (ikke synlig) 
** De andre kodeverdiene for synbarhet (1 og 2) benyttes ikke i AR5. 

Det er en egenskap ved klassifikasjonssystemet og naturen at identifisering av grenser i AR5 krever bruk av skjønn. Man skal derfor angi dårlig nøyaktighet og usikkerhet bare i tilfeller man har unormalt dårlige forutsetninger for å gjøre riktig registrering. Se AR5 klassifikasjonssystem for mer detaljerte regler. 

*Klassifiseringsmetode*

Spesiell egenskap for AR5 for å angi metode for klassifisering av areal (flater). Klassifiseringsmetoden angir også hvor sikker metoden antas å være for å gi riktige klassifiseringsegenskaper (markslag). Se kodeliste på https://register.geonorge.no/sosi-kodelister/fkb/ar5/5.0/klassifiseringsmetode[geonorge.no].

De mest vanlige klassifiseringsmetodene for AR5 vil være «Sikker klassifisering ved befaring i felt» (sFelt) og «Sikker klassifisering fra ortofoto på skjerm» (sOrto). 

*Datoegenskaper*

Ved ajourhold skal endrede objekter merkes med riktig Datafangst- og Verifiseringsdato. «Riktig» dato bestemmes av grunnlaget som benyttes ved ajourholdet. Er grunnlaget flybilde/ortofoto, skal Datafangst- og Verifiseringsdato settes lik fotograferingstidspunkt. Er grunnlaget «manus» laget ved feltbefaring, skal datoene settes lik tidspunkt for befaring. 

*Opphav*

Når kommunen ajourfører AR5 (kontinuerlig ajourhold) settes opphav til «Kommune». 
Når NIBIO ajourfører AR5 (periodisk ajourhold), settes opphav til «NIBIO».  
I tillegg er det definert noen spesielle kodeverdier som både forteller hvem som har ajourført og hvilket grunnlag som er benyttet.

Eksempel: Opphav ‘NIBIO-JM’ (objektet er henta fra NIBIO sin jordsmonnbase). 
Se verdier for opphav i egen kodeliste på https://register.geonorge.no/sosi-kodelister/fkb/ar5/5.0/opphav[geonorge.no]

*Informasjon*

Egenskapen Informasjon benyttes til kommunikasjon mellom NIBIO og kommune i periodisk ajourhold. Flater som NIBIO tror er klassifisert feil, men som NIBIO ikke greier å klassifisere, blir «merket» med Informasjon er lik: "NIBIO tror arealet kan være klassifisert feil. Kommunen må sjekke arealet". Dette blir gjort for at kommunen lett skal kunne finne, sjekke og rette flatene i kontinuerlig ajourhold.

<<<

== Metadata

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Metadataspesifikasjon

include::../felles/kap13_metadata.adoc[]

<<<


[appendix]
== SOSI-format-realisering

SOSI-realiseringen følger kravene i "Realisering i SOSI-foramt 5.0" <<SOSI-FORMAT>>. Under en utlisting av SOSI-formatrealiseringen:

include::SOSIformatRealisering.adoc[]


[appendix]
== GML-realisering

GML-realiseringen følger kravene i "Realisering i GML-format 5.0" <<SOSI-GML>>. Realiseringen defineres av følgende filer:

* link:{skjema-url}/FKBAR5.xsd[GML-Schema]
* link:{skjema-url}/eksempel/[Katalog med eksempelfiler]


[appendix]
== Lovlige egenskapskombinasjoner

include::egenskapskombinasjoner.adoc[]

:sectnums!:

<<<

[discrete]
== Lisensvilkår

// Inkluder lisensvilkår
include::../felles/lisensvilkaar.adoc[]
